Question 1 :- Your first task will be to create two numpy arrays, one with the help of linspace and another with the help of arange. 

The first array will be an array of length 20, having multiples of 2, starting from 20.
The second array will be an array of length 20, having multiples of 3, starting from 21, of type integer.

Note :- There shouldn't be elements repeated in any of the lists, that is, all the elements should be unique.

In [ ]:
import numpy as np
arr1=np.linspace(20,60,20,dtype=int,endpoint=False)
arr2=np.arange(21,81,3,dtype=int)
#print(len(arr1))
#print(len(arr2))
print("Multiples of 2:",arr1)
print("Multiples of 3:",arr2)

Multiples of 2: [20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]
Multiples of 3: [21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78]


Question 2:- From the two numpy arrays above, write a simple python script to find the common elements between both the arrays.

In [ ]:
print(np.intersect1d(arr1,arr2))

[24 30 36 42 48 54]


Question 3 - Now, since you have two arrays of equal length, using numpy, vertically stack both the arrays so as to form a 2D array of dimensions (2, 20)

In [ ]:
output=np.vstack((arr1,arr2))
print(output)

[[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]
 [21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78]]


Question 4 :- Reshape the 2D array formed in Question 3, into a new array of shape (8, 5)

In [ ]:
output1=output.reshape(8,5)
print(output1)


[[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [21 24 27 30 33]
 [36 39 42 45 48]
 [51 54 57 60 63]
 [66 69 72 75 78]]


Question 5:- Now, using the new array of shape (8, 5), distribute this array into 8 different 1D arrays representing the 8 rows of the 2D array, and then using numpy, compute the mean of each row.

In [37]:
for i in range(len(output1)):
  print(output1[i])
  print(np.mean(output1[i]))


[20 22 24 26 28]
24.0
[30 32 34 36 38]
34.0
[40 42 44 46 48]
44.0
[50 52 54 56 58]
54.0
[21 24 27 30 33]
27.0
[36 39 42 45 48]
42.0
[51 54 57 60 63]
57.0
[66 69 72 75 78]
72.0


Question 6:- Finally, find the mean and median of the 2D array using numpy, and print the absolute difference between them.

In [39]:
Mean=np.mean(output1)
Median=np.median(output1)
print(Mean)
print(Median)
print(np.absolute(Mean-Median))

44.25
43.0
1.25
